name       : ant-gtk-theme
version    : 1.1.0
release    : 1 
source     :
    - https://github.com/EliverLara/Ant/archive/v1.1.0.tar.gz : 79cbf36368592fb005f024076a924518695daee703635dc576a3a9d622f0381d
license    : GPL-3.0
component  : desktop.themes
summary    : A flat and light theme with a modern look
description: |
    A flat and light theme with a modern look
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant/index.theme
