name       : ant-gtk-theme
version    : 1.3.0
release    : 3
source     :
    - https://github.com/EliverLara/Ant/archive/v1.3.0.tar.gz : 1a00d72b48027dd6e160b7238ae408b27083d84e7432f37a47259ad3a067fceb
license    : GPL-3.0-or-later
component  : desktop.themes
summary    : A flat and light theme with a modern look
description: |
    A flat and light theme with a modern look
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant/index.theme
