name       : ant-gtk-theme
version    : 1.2.0
release    : 2
source     :
    - https://github.com/EliverLara/Ant/archive/v1.2.0.tar.gz : f674516681d51ef1c87fe775655879b811f203448946d5a52beddc38f0bfe780
license    : GPL-3.0
component  : desktop.themes
summary    : A flat and light theme with a modern look
description: |
    A flat and light theme with a modern look
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant/index.theme
